# Imagen de base para todos los jobs
image: node:23.1.0

# Manifiestos provistos por gitlab que extienden los stages del actual
# include:


# Variables globales de entorno
variables:
  SEARCH_MAX_DEPTH: 17 # No tengo idea de qué es esto
  MICROSERVICE_ORQUESTADOR: "orquestador"
  MICROSERVICE_SCHEDULER: "scheduler"
  MICROSERVICE_TASK_SERVICE: "task_service"
  MICROSERVICE_WORKFLOW_MANAGER: "wf_manager"
  MICROSERVICES: "${MICROSERVICE_ORQUESTADOR} ${MICROSERVICE_SCHEDULER} ${MICROSERVICE_TASK_SERVICE} ${MICROSERVICE_WORKFLOW_MANAGER}"
  CACHE_KEY: "cache-$(for service in ${MICROSERVICES}; do cat $service/package-lock.json; done | sha256sum | awk '{ print $1 }')"
  # Agregamos los jobs acá???

stages:
  - prepare
  - test
  - build
  - release_approval
  - release
  - deploy


cache-job:
  stage: prepare
  cache:
    key: ${CACHE_KEY}
    paths:
      - ./*/.npm/
      - ./*/node_modules/
      - ./*/package-lock.json.sha256sum
    policy: pull-push
    when: on_failure
  script:
    - CI_CACHE_EXIT_CODE=0
    - for service in ${MICROSERVICES}; do
        hash=$(cat $service/package-lock.json | sha256sum | awk '{ print $1 }');
        if [ -f $service/package-lock.json.sha256sum ]; then
          if [ "$(cat $service/package-lock.json.sha256sum)" != "$hash" ]; then
            CI_CACHE_EXIT_CODE=123;
          fi;
        fi;
        echo $hash > $service/package-lock.json.sha256sum;
      done
    - if [ $CI_CACHE_EXIT_CODE -ne 0 ]; then
        for service in ${MICROSERVICES}; do
          cd $service;
          npm ci --cache .npm --prefer-offline;
          cd ..;
        done;
      fi
    - exit $CI_CACHE_EXIT_CODE


.node-job:
  cache:
    key: ${CACHE_KEY}
    paths:
      - ${SERVICE_NAME}/.npm/
      - ${SERVICE_NAME}/node_modules/
    policy: pull
  needs:
    - job: cache-job
      optional: false


.unit-test:
  extends: .node-job
  stage: test
  script:
    - cd ${SERVICE_NAME}
    - npm install
    - JEST_JUNIT_OUTPUT_FILE='test-results.xml' npm run test -- --ci --reporters=default --reporters=jest-junit
  artifacts:
    reports:
      junit: ${SERVICE_NAME}/test-results.xml
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/  # Ensure it doesn't run on version tags
      when: never
    - when: always

.build:
  extends: .node-job
  stage: build
  script:
    - cd ${SERVICE_NAME}
    - npm install
    - npm run build
  artifacts:
    paths:
      - ${SERVICE_NAME}/dist/ 
    expire_in: 30 days
  rules:
    - when: always

.release:
  stage: release
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ${SERVICE_NAME}
    - docker build -t $CI_REGISTRY_IMAGE/${SERVICE_NAME}:${CI_COMMIT_TAG} -f Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/${SERVICE_NAME}:${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: on_success
  needs:
    - job: release_approval
      optional: false


.deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "Deploy ${SERVICE_NAME} to Kubernetes cluster"
    - echo "Updating deployment for ${SERVICE_NAME} with image ${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${CI_COMMIT_TAG}"
    - echo "kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${CI_COMMIT_TAG}"
    - echo "kubectl rollout status deployment/${SERVICE_NAME}"
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: on_success
  needs:
    - job: release_approval
      optional: false


# Job de aprobación manual de release
release_approval:
  stage: release_approval
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: always
  script:
    - echo "Release $CI_COMMIT_TAG has been approved for deployment."
  when: manual
  allow_failure: false


# Jobs específicos de cada microservicio
orquestador-unit-tests:
  extends: .unit-test
  variables:
    SERVICE_NAME: $MICROSERVICE_ORQUESTADOR

# scheduler-unit-tests:
#   extends: .unit-test
#   variables:
#     SERVICE_NAME: $MICROSERVICE_SCHEDULER

# task-service-unit-tests:
#   extends: .unit-test
#   variables:
#     SERVICE_NAME: $MICROSERVICE_TASK_SERVICE

# workflow-manager-unit-tests:
#   extends: .unit-test
#   variables:
#     SERVICE_NAME: $MICROSERVICE_WORKFLOW_MANAGER

orquestador-build:
  extends: .build
  variables:
    SERVICE_NAME: $MICROSERVICE_ORQUESTADOR

scheduler-build:
  extends: .build
  variables:
    SERVICE_NAME: $MICROSERVICE_SCHEDULER

task-service-build:
  extends: .build
  variables:
    SERVICE_NAME: $MICROSERVICE_TASK_SERVICE

workflow-manager-build:
  extends: .build
  variables:
    SERVICE_NAME: $MICROSERVICE_WORKFLOW_MANAGER

orquestador-release:
  extends: .release
  variables:
    SERVICE_NAME: $MICROSERVICE_ORQUESTADOR

scheduler-release:
  extends: .release
  variables:
    SERVICE_NAME: $MICROSERVICE_SCHEDULER

task-service-release:
  extends: .release
  variables:
    SERVICE_NAME: $MICROSERVICE_TASK_SERVICE

workflow-manager-release:
  extends: .release
  variables:
    SERVICE_NAME: $MICROSERVICE_WORKFLOW_MANAGER

orquestador-deploy:
  extends: .deploy
  variables:
    SERVICE_NAME: $MICROSERVICE_ORQUESTADOR
  needs:
    - job: release_approval
      optional: false
    - job: orquestador-release
      optional: false

scheduler-deploy:
  extends: .deploy
  variables:
    SERVICE_NAME: $MICROSERVICE_SCHEDULER
  needs:
    - job: release_approval
      optional: false
    - job: scheduler-release
      optional: false

task-service-deploy:
  extends: .deploy
  variables:
    SERVICE_NAME: $MICROSERVICE_TASK_SERVICE
  needs:
    - job: release_approval
      optional: false
    - job: task-service-release
      optional: false

workflow-manager-deploy:
  extends: .deploy
  variables:
    SERVICE_NAME: $MICROSERVICE_WORKFLOW_MANAGER
  needs:
    - job: release_approval
      optional: false
    - job: workflow-manager-release
      optional: false

