export enum StepScheduleException {
  TASK_NOT_EXISTS = "TASK_NOT_EXISTS",
  TASK_PARAM_NOT_EXISTS = "TASK_PARAM_NOT_EXISTS",
  TASK_PARAM_MISSING = "TASK_PARAM_MISSING",
  TASK_ERROR = "TASK_ERROR",
}
